[config]
schemaVersion = "0.0.1"

[package]
namespace = "Syrupdesu"
name = "LCChineseFont"
description = "添加完整中文字体支持，并修复中文 IME 输入。"
websiteUrl = "https://github.com/Syrupdesu/LC-ChineseFont"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"
[[build.copy]]
source = "./build"
target = "plugins/"
[[build.copy]]
source = "./LICENSE"
target = "/"
[[build.copy]]
source = "./licenses"
target = "licenses"
[[build.copy]]
source = "./assets"
target = "config/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company" ]
[publish.categories]
lethal-company = [ "bepinex", "client-side", "tools", "misc" ]
